steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'amazingapp/blue/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/amazingapp:$COMMIT_SHA', 'amazingapp/blue']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/amazingapp:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'amazingapp'
      - '--image'
      - 'gcr.io/$PROJECT_ID/amazingapp:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/amazingapp:$COMMIT_SHA'

logsBucket: 'gs://asif-logs'
